name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.5.x', '2.6.x' ]

    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install bundler
      run: |
        gem install bundler

    - name: Cache bundled gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-gem-${{ hashFiles('**/ializer.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/ializer.gemspec') }}
          ${{ runner.os }}-${{ matrix.ruby }}-

    - name: Bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: RSpec
      run: |
        bundle exec rspec

    - name: Rubocop
      run: |
        bundle exec rubocop -c .rubocop.yml
