name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]

    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install bundler
      run: |
        gem install bundler

    - name: Bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: RSpec
      run: |
        bundle exec rspec

    - name: Rubocop
      run: |
        bundle exec rubocop -c .rubocop.yml
